### PR TITLE
Support for Bootstrap v4.0.0 alpha 6

### PR DESCRIPTION
**Pull request by rabrowne85**
I've updated a number of the files to make this plugin work with the latest alpha release of Bootstrap. I've worked my way through the different themes, and made the small adjustments to each - generally speaking the flexbox is utilised with v4, which means the `display: block;` is no longer required.

The test file needed to be adjusted as the `nav` tag is no longer used in Bootstap 4 (for some reason?). As such the count of `div`'s was being increased by 1.

The "optional theme" is also not available for v4, so I've used another theme from Bootswatch which seemed to be a close match to the theme you had.

I think I've covered everything that's needed, but let me know - this is my first pull-request.

Let me know if you have any comments/questions.

### CODE REVIEW

**Comment by techlab** [comment]
Thank you for your awesome contribution. 
Can you please create the pull request to [`dev`](https://github.com/techlab/SmartWizard/tree/dev) branch so I would be able to test before going live?

**Comment by rabrowne85** [comment]
No problems :thumbsup:. I've updated the pull request to the `dev` branch. If I can be of any further help, let me know.

**Comment by techlab** [comment]
Thank you 👍, I will look into it soon

**Comment by ksidibe** [comment]
Any update on Bootstrap 4 support?
I just tried the plugin with Bootstrap 4 and it is not working.
Thanks.

**Pull request merged**
