### PR TITLE
Adding stepDirection parameter

### PR DESCRIPTION
**Pull request by metallurgical**
I'm need this behavior, so added it up. Maybe you can review it, and added it yourself with better solutions

### CODE REVIEW

**Comment by techlab** [comment]
Thank you for the code, I am already working on the changes in similar way, I will be pushing it soon. Thank you so much for your input.

**Comment by metallurgical** [comment]
Alright, please push it ASAP, as i need that functionality for my latest project. For now, i'm just stick to my modification.

**Comment by techlab** [comment]
Its been pushed, v4.0.5 have the change

**Comment by metallurgical** [comment]
Got it! Thanks

**Pull request closed without merging**
